name: Compile Project

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: mlugg/setup-zig@v1

      - name: Build Project
        run: zig build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zi
          path: zig-out/bin/zi
