name: Compile Project
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Build
        - uses: actions/checkout@v3
        - uses: mlugg/setup-zig@v1
        - run: zig build

        - name: Upload
        - uses: actions/upload-artifact@v4
        - with:
            name: zi 
            path: zig-out/bin/zi
